"""Ollama-backed local reasoning engine."""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from datetime import datetime
from json import JSONDecodeError
from typing import Literal, cast

from httpx import RequestError as HttpxRequestError
from httpx import TimeoutException as HttpxTimeoutException
from ollama import (
    ChatResponse,
    Client,
    ListResponse,
    ProgressResponse,
    RequestError,
    ResponseError,
    ShowResponse,
)
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator

from voice_concierge.reasoning.errors import (
    ReasoningBackendUnavailableError,
    ReasoningConfigurationError,
    ReasoningError,
    ReasoningGenerationError,
    ReasoningModelUnavailableError,
    ReasoningTimeoutError,
)
from voice_concierge.reasoning.models import (
    LocalModelDetails,
    LocalModelInfo,
    ModelDownloadProgress,
)
from voice_concierge.reasoning.output import apply_spoken_word_limit
from voice_concierge.reasoning.policy import apply_reasoning_policy_guards
from voice_concierge.reasoning.prompting import (
    DEFAULT_PROMPT_VERSION,
    build_granite_messages,
    load_prompt_template,
)
from voice_concierge.reasoning.types import (
    MemoryAction,
    ReasoningRequest,
    ReasoningResponse,
    ReasoningTrace,
)
from voice_concierge.reasoning.validation import validate_reasoning_request

_OLLAMA_CLIENT_ERRORS = (
    ConnectionError,
    HttpxRequestError,
    HttpxTimeoutException,
    JSONDecodeError,
    RequestError,
    ResponseError,
    ValidationError,
)
_MIN_PREDICT_TOKENS = 96
_PREDICT_TOKEN_OVERHEAD = 64
_PREDICT_TOKENS_PER_WORD = 4


class OllamaReasoningError(ReasoningError):
    """Raised when the local Ollama runner cannot produce a usable response."""


class OllamaBackendUnavailableError(
    ReasoningBackendUnavailableError,
    OllamaReasoningError,
):
    """Raised when the local Ollama runner cannot be reached for generation."""


class OllamaModelUnavailableError(
    ReasoningModelUnavailableError,
    OllamaReasoningError,
):
    """Raised when the selected Ollama model is unavailable during generation."""


class OllamaTimeoutError(
    ReasoningTimeoutError,
    OllamaReasoningError,
):
    """Raised when local Ollama generation exceeds the configured timeout."""


class OllamaGenerationError(
    ReasoningGenerationError,
    OllamaReasoningError,
):
    """Raised when local Ollama generation fails for another runtime reason."""


class OllamaModelManagementError(RuntimeError):
    """Raised when local Ollama model management fails."""


class _StructuredMemoryAction(BaseModel):
    """Validated memory-action payload generated by the model."""

    model_config = ConfigDict(extra="forbid", strict=True, str_strip_whitespace=True)

    action: Literal["store", "update", "delete"]
    content: str = Field(min_length=1)
    rationale: str = Field(min_length=1)
    target_key: str | None = Field(default=None, min_length=1)
    requires_confirmation: bool


class _StructuredReasoningResponse(BaseModel):
    """Single source for Ollama's output schema and response validation."""

    model_config = ConfigDict(extra="forbid", strict=True, str_strip_whitespace=True)

    spoken_response: str = Field(
        min_length=1,
        description="Short response intended to be spoken aloud.",
    )
    needs_confirmation: bool = Field(
        description="Whether the user must confirm before action is taken."
    )
    proposed_memory_action: _StructuredMemoryAction | None
    mode_suggestion: str | None
    confidence: Literal["low", "medium", "high"]
    required_information_source: Literal[
        "none",
        "user_input",
        "local_context",
        "stable_knowledge",
        "runtime_live",
        "external_live",
    ]
    freshness_requirement: Literal["not_required", "current"]

    @field_validator("mode_suggestion", mode="before")
    @classmethod
    def normalize_blank_mode_suggestion(cls, value: object) -> object:
        """Treat blank mode suggestions as absent rather than meaningful values."""

        if isinstance(value, str) and not value.strip():
            return None
        return value


@dataclass(frozen=True)
class OllamaConfig:
    """Configuration for the local Ollama reasoning backend."""

    model: str
    host: str = "http://localhost:11434"
    timeout_s: float = 120.0
    temperature: float = 0.2
    top_p: float = 0.9
    num_ctx: int = 4096
    max_predict_tokens: int = 512
    keep_alive: str | float = "5m"
    prompt_version: str = DEFAULT_PROMPT_VERSION

    def __post_init__(self) -> None:
        _validate_config_string(self.model, "model")
        _validate_config_string(self.host, "host")
        _validate_config_string(self.prompt_version, "prompt_version")
        _validate_positive_number(self.timeout_s, "timeout_s")
        _validate_temperature(self.temperature)
        _validate_top_p(self.top_p)
        _validate_positive_integer(self.num_ctx, "num_ctx")
        _validate_positive_integer(self.max_predict_tokens, "max_predict_tokens")
        _validate_keep_alive(self.keep_alive)


class OllamaReasoningEngine:
    """Reasoning engine that calls a local Ollama runner."""

    def __init__(self, config: OllamaConfig, client: Client | None = None) -> None:
        self.config = config
        self._prompt_template = load_prompt_template(config.prompt_version)
        self._client = (
            client
            if client is not None
            else Client(host=config.host, timeout=config.timeout_s)
        )

    def generate(self, request: ReasoningRequest) -> ReasoningResponse:
        return self.generate_trace(request).guarded_response

    def generate_trace(self, request: ReasoningRequest) -> ReasoningTrace:
        """Return parsed and policy-guarded responses from one Ollama request."""

        validate_reasoning_request(request)
        generation_options = _generation_options_for_request(request, self.config)
        messages = [
            message.as_dict()
            for message in build_granite_messages(
                request,
                prompt_version=self.config.prompt_version,
            )
        ]
        try:
            response = cast(
                ChatResponse,
                self._client.chat(
                    model=self.config.model,
                    messages=messages,
                    stream=False,
                    format=_StructuredReasoningResponse.model_json_schema(),
                    options={
                        "temperature": self.config.temperature,
                        "top_p": self.config.top_p,
                        "num_ctx": generation_options.num_ctx,
                        "num_predict": generation_options.num_predict,
                    },
                    keep_alive=generation_options.keep_alive,
                ),
            )
        except _OLLAMA_CLIENT_ERRORS as exc:
            raise _generation_error_from_client_error(exc, self.config.host) from exc

        content = self._extract_content(response)
        metadata = {
            "backend": "ollama",
            "model": self.config.model,
            "output_format": "structured_json",
            "prompt_id": self._prompt_template.prompt_id,
            "prompt_version": self._prompt_template.version,
            **generation_options.as_metadata(),
            **self._extract_metrics(response),
        }
        raw_response = self._parse_response_content(content, metadata)
        guarded_response = apply_reasoning_policy_guards(request, raw_response)
        guarded_response = apply_spoken_word_limit(
            guarded_response,
            request.constraints.max_words,
        )
        return ReasoningTrace(
            raw_response=raw_response,
            guarded_response=guarded_response,
        )

    def _extract_content(self, response: ChatResponse) -> str:
        content = response.message.content
        if not isinstance(content, str) or not content.strip():
            raise OllamaGenerationError("Ollama response message was empty.")
        return content.strip()

    def _parse_response_content(
        self,
        content: str,
        metadata: dict[str, str],
    ) -> ReasoningResponse:
        try:
            payload = _StructuredReasoningResponse.model_validate_json(
                _strip_json_fence(content)
            )
        except ValidationError as exc:
            invalid_json = any(
                error["type"] == "json_invalid" for error in exc.errors()
            )
            if invalid_json:
                return ReasoningResponse(
                    spoken_response=(
                        "I could not produce a valid structured response."
                    ),
                    confidence="low",
                    metadata={
                        **metadata,
                        "structured_parse_error": "invalid_json",
                    },
                )
            return ReasoningResponse(
                spoken_response="I could not produce a valid structured response.",
                confidence="low",
                metadata={
                    **metadata,
                    "structured_parse_error": "schema_validation_failed",
                },
            )

        return _response_from_structured_payload(payload, metadata)

    def _extract_metrics(self, response: ChatResponse) -> dict[str, str]:
        metric_keys = (
            "total_duration",
            "load_duration",
            "prompt_eval_count",
            "prompt_eval_duration",
            "eval_count",
            "eval_duration",
        )
        return {
            key: str(value)
            for key in metric_keys
            if isinstance((value := getattr(response, key)), int)
        }


@dataclass(frozen=True)
class OllamaModelManagerConfig:
    """Configuration for Ollama model management."""

    host: str = "http://localhost:11434"
    timeout_s: float = 180.0


class OllamaModelManager:
    """Model-management client for a local Ollama runner."""

    def __init__(
        self,
        config: OllamaModelManagerConfig | None = None,
        client: Client | None = None,
    ) -> None:
        self.config = config or OllamaModelManagerConfig()
        self._client = (
            client
            if client is not None
            else Client(
                host=self.config.host,
                timeout=self.config.timeout_s,
            )
        )

    def list_models(self) -> tuple[LocalModelInfo, ...]:
        try:
            response = self._client.list()
            return tuple(_model_info_from_response(model) for model in response.models)
        except _OLLAMA_CLIENT_ERRORS as exc:
            raise OllamaModelManagementError(
                _client_error_message(exc, self.config.host)
            ) from exc

    def show_model(self, model: str) -> LocalModelDetails:
        model_name = _validated_model_name(model)
        try:
            response = self._client.show(model_name)
            return _model_details_from_response(model_name, response)
        except _OLLAMA_CLIENT_ERRORS as exc:
            raise OllamaModelManagementError(
                _client_error_message(exc, self.config.host)
            ) from exc

    def pull_model(
        self,
        model: str,
        *,
        stream: bool = False,
    ) -> tuple[ModelDownloadProgress, ...]:
        model_name = _validated_model_name(model)
        try:
            result = self._client.pull(model_name, stream=stream)
            if not stream:
                response = cast(ProgressResponse, result)
                return (_download_progress_from_response(response),)

            updates = cast(Iterator[ProgressResponse], result)
            return tuple(_download_progress_from_response(update) for update in updates)
        except _OLLAMA_CLIENT_ERRORS as exc:
            raise OllamaModelManagementError(
                _client_error_message(exc, self.config.host)
            ) from exc


@dataclass(frozen=True)
class _GenerationOptions:
    num_ctx: int
    num_predict: int
    keep_alive: str | float
    temperature: float
    top_p: float
    max_predict_tokens: int

    def as_metadata(self) -> dict[str, str]:
        return {
            "num_ctx": str(self.num_ctx),
            "num_predict": str(self.num_predict),
            "max_predict_tokens": str(self.max_predict_tokens),
            "keep_alive": str(self.keep_alive),
            "temperature": str(self.temperature),
            "top_p": str(self.top_p),
        }


def _generation_options_for_request(
    request: ReasoningRequest,
    config: OllamaConfig,
) -> _GenerationOptions:
    return _GenerationOptions(
        num_ctx=config.num_ctx,
        num_predict=_num_predict_for_word_limit(
            request.constraints.max_words,
            max_predict_tokens=config.max_predict_tokens,
        ),
        keep_alive=config.keep_alive,
        temperature=config.temperature,
        top_p=config.top_p,
        max_predict_tokens=config.max_predict_tokens,
    )


def _num_predict_for_word_limit(
    max_words: int,
    *,
    max_predict_tokens: int,
) -> int:
    estimate = (max_words * _PREDICT_TOKENS_PER_WORD) + _PREDICT_TOKEN_OVERHEAD
    return min(
        max_predict_tokens,
        max(_MIN_PREDICT_TOKENS, estimate),
    )


def _generation_error_from_client_error(
    exc: Exception,
    host: str,
) -> OllamaReasoningError:
    message = _client_error_message(exc, host)
    if isinstance(exc, (HttpxTimeoutException, TimeoutError)):
        return OllamaTimeoutError(message)
    if isinstance(exc, ResponseError):
        if exc.status_code == 404:
            return OllamaModelUnavailableError(message)
        return OllamaGenerationError(message)
    if isinstance(exc, (ConnectionError, HttpxRequestError, RequestError)):
        return OllamaBackendUnavailableError(message)
    return OllamaGenerationError(message)


def _client_error_message(exc: Exception, host: str) -> str:
    if isinstance(exc, ResponseError):
        return f"Ollama request failed: {exc}"
    if isinstance(exc, HttpxRequestError):
        return f"Could not complete local Ollama request to {host}: {exc}"
    if isinstance(
        exc,
        JSONDecodeError | RequestError | ValidationError,
    ):
        return f"Ollama request or response was invalid: {exc}"
    return f"Could not reach local Ollama runner at {host}: {exc}"


def _validate_config_string(value: object, field_name: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ReasoningConfigurationError(
            f"Ollama config {field_name} must be a non-empty string."
        )


def _validate_positive_number(value: object, field_name: str) -> None:
    if not isinstance(value, (int, float)) or isinstance(value, bool) or value <= 0:
        raise ReasoningConfigurationError(
            f"Ollama config {field_name} must be greater than 0."
        )


def _validate_positive_integer(value: object, field_name: str) -> None:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise ReasoningConfigurationError(
            f"Ollama config {field_name} must be a positive integer."
        )


def _validate_temperature(value: object) -> None:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ReasoningConfigurationError("Ollama config temperature must be a number.")
    if value < 0 or value > 2:
        raise ReasoningConfigurationError(
            "Ollama config temperature must be between 0 and 2."
        )


def _validate_top_p(value: object) -> None:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ReasoningConfigurationError("Ollama config top_p must be a number.")
    if value <= 0 or value > 1:
        raise ReasoningConfigurationError(
            "Ollama config top_p must be greater than 0 and at most 1."
        )


def _validate_keep_alive(value: object) -> None:
    if isinstance(value, str) and value.strip():
        return
    if isinstance(value, (int, float)) and not isinstance(value, bool) and value > 0:
        return
    raise ReasoningConfigurationError(
        "Ollama config keep_alive must be a non-empty string or positive number."
    )


def _response_from_structured_payload(
    payload: _StructuredReasoningResponse,
    metadata: dict[str, str],
) -> ReasoningResponse:
    proposed_memory_action = None
    if payload.proposed_memory_action is not None:
        action = payload.proposed_memory_action
        proposed_memory_action = MemoryAction(
            action=action.action,
            content=action.content,
            rationale=action.rationale,
            target_key=action.target_key,
            requires_confirmation=action.requires_confirmation,
        )

    needs_confirmation = payload.needs_confirmation
    if proposed_memory_action and proposed_memory_action.requires_confirmation:
        needs_confirmation = True

    return ReasoningResponse(
        spoken_response=payload.spoken_response,
        needs_confirmation=needs_confirmation,
        proposed_memory_action=proposed_memory_action,
        mode_suggestion=payload.mode_suggestion,
        confidence=payload.confidence,
        required_information_source=payload.required_information_source,
        freshness_requirement=payload.freshness_requirement,
        metadata=metadata,
    )


def _strip_json_fence(content: str) -> str:
    stripped = content.strip()
    if not stripped.startswith("```"):
        return stripped

    lines = stripped.splitlines()
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


def _model_info_from_response(value: ListResponse.Model) -> LocalModelInfo:
    model = _required_model_string(value.model)
    details = value.details
    return LocalModelInfo(
        name=model,
        model=model,
        modified_at=_optional_datetime(value.modified_at),
        size_bytes=_optional_int(value.size),
        digest=_optional_string(value.digest),
        format=_optional_string(details.format if details else None),
        family=_optional_string(details.family if details else None),
        families=_string_tuple(details.families if details else None),
        parameter_size=_optional_string(details.parameter_size if details else None),
        quantization_level=_optional_string(
            details.quantization_level if details else None
        ),
    )


def _model_details_from_response(
    model: str,
    response: ShowResponse,
) -> LocalModelDetails:
    details = response.details
    return LocalModelDetails(
        model=model,
        modified_at=_optional_datetime(response.modified_at),
        format=_optional_string(details.format if details else None),
        family=_optional_string(details.family if details else None),
        families=_string_tuple(details.families if details else None),
        parameter_size=_optional_string(details.parameter_size if details else None),
        quantization_level=_optional_string(
            details.quantization_level if details else None
        ),
        capabilities=_string_tuple(response.capabilities),
        parameters=_optional_string(response.parameters),
        license=_optional_string(response.license),
    )


def _download_progress_from_response(
    response: ProgressResponse,
) -> ModelDownloadProgress:
    status = response.status
    if not isinstance(status, str) or not status.strip():
        raise OllamaModelManagementError("Ollama pull response missing status.")

    return ModelDownloadProgress(
        status=status.strip(),
        digest=_optional_string(response.digest),
        total=_optional_int(response.total),
        completed=_optional_int(response.completed),
    )


def _validated_model_name(model: str) -> str:
    if not isinstance(model, str) or not model.strip():
        raise ValueError("Model name must be a non-empty string.")
    return model.strip()


def _required_model_string(value: object) -> str:
    if not isinstance(value, str) or not value.strip():
        raise OllamaModelManagementError("Ollama model entry missing model name.")
    return value.strip()


def _optional_string(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        stripped = value.strip()
        return stripped or None
    return str(value)


def _optional_datetime(value: datetime | None) -> str | None:
    return value.isoformat() if value else None


def _optional_int(value: object) -> int | None:
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, int):
        return int(value)
    return None


def _string_tuple(value: object) -> tuple[str, ...]:
    if not isinstance(value, list | tuple):
        return ()
    return tuple(
        item.strip() for item in value if isinstance(item, str) and item.strip()
    )
